name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Java JDK 17 einrichten
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle ohne Wrapper ausführen
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.5'

      - name: APK bauen
        run: gradle assembleDebug --stacktrace

      - name: APK hochladen
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: "**/build/outputs/apk/**/*.apk"
          
